name: shopping_list_app
description: A simple shopping list app.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.12.0+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1
  google_fonts: ^0.3.10
  nice_button: ^0.1.7
  flutter_slidable: "^0.5.4"
  flutter_platform_widgets: ^0.32.5

flutter:
  uses-material-design: true
